import NavHeader from '@/components/NavHeader';
import SessionProvider from '@/components/SessionProvider';
import type { Metadata } from "next";
import { getServerSession } from 'next-auth';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <SessionProvider session={session}>
          <NavHeader />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
